In [16]:
import pandas as pd
df = pd.read_csv("temperatures.csv")
df.head()

,year,month,day,week,temp_2,temp_1,average,actual,forecast_noaa,forecast_acc,forecast_under,friend
0,2016,1,1,Fri,45,45,45.6,45,43,50,44,29
1,2016,1,2,Sat,44,45,45.7,44,41,50,44,61
2,2016,1,3,Sun,45,44,45.8,41,43,46,47,56
3,2016,1,4,Mon,44,41,45.9,40,44,48,46,53
4,2016,1,5,Tues,41,40,46.0,44,46,46,46,41

In [17]:
df.describe()

,year,month,day,temp_2,temp_1,average,actual,forecast_noaa,forecast_acc,forecast_under,friend
count,348.0,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000,348.000000
mean,2016.0,6.477011,15.514368,62.652299,62.701149,59.760632,62.543103,57.238506,62.373563,59.772989,60.034483
std,0.0,3.498380,8.772982,12.165398,12.120542,10.527306,11.794146,10.605746,10.549381,10.705256,15.626179
min,2016.0,1.000000,1.000000,35.000000,35.000000,45.100000,35.000000,41.000000,46.000000,44.000000,28.000000
25%,2016.0,3.000000,8.000000,54.000000,54.000000,49.975000,54.000000,48.000000,53.000000,50.000000,47.750000
50%,2016.0,6.000000,15.000000,62.500000,62.500000,58.200000,62.500000,56.000000,61.000000,58.000000,60.000000
75%,2016.0,10.000000,23.000000,71.000000,71.000000,69.025000,71.000000,66.000000,72.000000,69.000000,71.000000
max,2016.0,12.000000,31.000000,117.000000,117.000000,77.400000,92.000000,77.000000,82.000000,79.000000,95.000000

In [19]:
features = pd.get_dummies(df) # One-hot encode the data using pandas get_dummies
features.iloc[:,5:].head(5)

,average,actual,forecast_noaa,forecast_acc,forecast_under,friend,week_Fri,week_Mon,week_Sat,week_Sun,week_Thurs,week_Tues,week_Wed
0,45.6,45,43,50,44,29,1,0,0,0,0,0,0
1,45.7,44,41,50,44,61,0,0,1,0,0,0,0
2,45.8,41,43,46,47,56,0,0,0,1,0,0,0
3,45.9,40,44,48,46,53,0,1,0,0,0,0,0
4,46.0,44,46,46,46,41,0,0,0,0,0,1,0

In [34]:
features['actual']

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [35]:
import numpy as np
labels = np.array(features["actual"])
labels

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [22]:
features= features.drop('actual', axis = 1)
features

,year,month,day,temp_2,temp_1,average,forecast_noaa,forecast_acc,forecast_under,friend,week_Fri,week_Mon,week_Sat,week_Sun,week_Thurs,week_Tues,week_Wed
0,2016,1,1,45,45,45.6,43,50,44,29,1,0,0,0,0,0,0
1,2016,1,2,44,45,45.7,41,50,44,61,0,0,1,0,0,0,0
2,2016,1,3,45,44,45.8,43,46,47,56,0,0,0,1,0,0,0
3,2016,1,4,44,41,45.9,44,48,46,53,0,1,0,0,0,0,0
4,2016,1,5,41,40,46.0,46,46,46,41,0,0,0,0,0,1,0
5,2016,1,6,40,44,46.1,43,49,48,40,0,0,0,0,0,0,1
6,2016,1,7,44,51,46.2,45,49,46,38,0,0,0,0,1,0,0
7,2016,1,8,51,45,46.3,43,47,46,34,1,0,0,0,0,0,0
8,2016,1,9,45,48,46.4,46,50,45,47,0,0,1,0,0,0,0
9,2016,1,10,48,50,46.5,45,48,48,49,0,0,0,1,0,0,0
10,2016,1,11,50,52,46.7,42,48,48,39,0,1,0,0,0,0,0
11,2016,1,12,52,45,46.8,44,50,45,61,0,0,0,0,0,1,0
12,2016,1,13,45,49,46.9,45,51,46,33,0,0,0,0,0,0,1
13,2016,1,14,49,55,47.0,43,47,46,58,0,0,0,0,1,0,0
14,2016,1,15,55,49,47.1,46,51,46,65,1,0,0,0,0,0,0
15,2016,1,16,49,48,47.3,45,52,46,28,0,0,1,0,0,0,0
16,2016,1,17,48,54,47.4,45,51,46,47,0,0,0,1,0,0,0
17,2016,1,18,54,50,47.5,44,48,49,58,0,1,0,0,0,0,0
18,2016,1,19,50,54,47.6,47,49,48,53,0,0,0,0,0,1,0
19,2016,1,20,54,48,47.7,44,52,49,61,0,0,0,0,0,0,1
20,2016,1,21,48,52,47.8,43,51,46,57,0,0,0,0,1,0,0
21,2016,1,22,52,52,47.9,47,48,48,60,1,0,0,0,0,0,0
22,2016,1,23,52,57,48.0,45,49,50,37,0,0,1,0,0,0,0
23,2016,1,24,57,48,48.1,46,50,48,54,0,0,0,1,0,0,0
24,2016,1,25,48,51,48.2,45,51,49,63,0,1,0,0,0,0,0
25,2016,1,26,51,54,48.3,44,53,50,61,0,0,0,0,0,1,0
26,2016,1,27,54,56,48.4,45,51,49,54,0,0,0,0,0,0,1
27,2016,1,28,56,57,48.4,44,52,48,34,0,0,0,0,1,0,0
28,2016,1,29,57,56,48.5,48,52,47,49,1,0,0,0,0,0,0
29,2016,1,30,56,52,48.6,45,51,48,47,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,2016,12,2,52,46,47.2,46,51,49,41,1,0,0,0,0,0,0
319,2016,12,3,46,50,47.0,42,52,47,58,0,0,1,0,0,0,0
320,2016,12,4,50,49,46.8,45,47,47,53,0,0,0,1,0,0,0
321,2016,12,5,49,46,46.6,43,50,45,65,0,1,0,0,0,0,0
322,2016,12,6,46,40,46.4,44,50,45,56,0,0,0,0,0,1,0
323,2016,12,7,40,42,46.3,44,51,46,62,0,0,0,0,0,0,1
324,2016,12,8,42,40,46.1,45,51,47,36,0,0,0,0,1,0,0
325,2016,12,9,40,41,46.0,43,51,44,54,1,0,0,0,0,0,0
326,2016,12,10,41,36,45.9,44,48,44,65,0,0,1,0,0,0,0
327,2016,12,11,36,44,45.7,41,46,47,35,0,0,0,1,0,0,0
328,2016,12,12,44,44,45.6,43,50,45,42,0,1,0,0,0,0,0
329,2016,12,13,44,43,45.5,41,47,46,46,0,0,0,0,0,1,0
330,2016,12,14,43,40,45.4,45,48,45,49,0,0,0,0,0,0,1
331,2016,12,15,40,39,45.3,45,49,47,46,0,0,0,0,1,0,0
332,2016,12,16,39,39,45.3,44,49,44,39,1,0,0,0,0,0,0
333,2016,12,17,39,35,45.2,43,47,46,38,0,0,1,0,0,0,0
334,2016,12,18,35,35,45.2,44,46,46,36,0,0,0,1,0,0,0
335,2016,12,19,35,39,45.1,42,46,45,51,0,1,0,0,0,0,0
336,2016,12,20,39,46,45.1,45,49,45,62,0,0,0,0,0,1,0
337,2016,12,21,46,51,45.1,44,50,46,39,0,0,0,0,0,0,1
338,2016,12,22,51,49,45.1,42,47,46,38,0,0,0,0,1,0,0
339,2016,12,23,49,45,45.1,45,49,44,35,1,0,0,0,0,0,0
340,2016,12,24,45,40,45.1,44,47,46,39,0,0,1,0,0,0,0
341,2016,12,25,40,41,45.1,42,49,44,31,0,0,0,1,0,0,0
342,2016,12,26,41,42,45.2,45,48,46,58,0,1,0,0,0,0,0
343,2016,12,27,42,42,45.2,41,50,47,47,0,0,0,0,0,1,0
344,2016,12,28,42,47,45.3,41,49,44,58,0,0,0,0,0,0,1
345,2016,12,29,47,48,45.3,43,50,45,65,0,0,0,0,1,0,0
346,2016,12,30,48,48,45.4,44,46,44,42,1,0,0,0,0,0,0
347,2016,12,31,48,57,45.5,42,48,47,57,0,0,1,0,0,0,0

In [27]:
feature_list = list(features.columns)
feature_list

AttributeError: 'numpy.ndarray' object has no attribute 'columns'

In [ ]:
features = np.array(features)
features